import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";

const workspaceDir = vscode.workspace.workspaceFolders?.[0]?.uri?.fsPath || "";
const resultsFile = path.join(workspaceDir, "DEMO_CONTEXT_WINDOW_RESULTS.md");

/**
 * Context Window Demo Extension
 *
 * Demonstrates how to read and access Copilot context:
 * - Active editor info
 * - Selection/cursor position
 * - Workspace info
 * - File content
 * - All open editors
 */

interface ContextSnapshot {
  timestamp: string;
  activeEditor?: {
    fileName: string;
    language: string;
    isDirty: boolean;
    lineCount: number;
    cursorLine: number;
    cursorCharacter: number;
    contentPreview: string;
  };
  selection?: {
    selectedText: string;
    selectionStart: { line: number; character: number };
    selectionEnd: { line: number; character: number };
  };
  workspace?: {
    name: string;
    folders: string[];
    fileCount: number;
  };
  openEditors: {
    fileName: string;
    language: string;
  }[];
}

/**
 * Capture current context window state
 */
function captureContextWindow(): ContextSnapshot {
  const activeEditor = vscode.window.activeTextEditor;
  const allEditors = vscode.window.visibleTextEditors;
  const workspace = vscode.workspace;

  const context: ContextSnapshot = {
    timestamp: new Date().toISOString(),
    openEditors: allEditors.map((ed) => ({
      fileName: path.basename(ed.document.fileName),
      language: ed.document.languageId,
    })),
  };

  // Capture active editor info
  if (activeEditor) {
    const doc = activeEditor.document;
    const selection = activeEditor.selection;
    const startLine = Math.max(0, selection.active.line - 2);
    const endLine = Math.min(doc.lineCount, selection.active.line + 3);
    const contentPreview = doc
      .getText(new vscode.Range(startLine, 0, endLine, 0))
      .substring(0, 200);

    context.activeEditor = {
      fileName: path.basename(doc.fileName),
      language: doc.languageId,
      isDirty: doc.isDirty,
      lineCount: doc.lineCount,
      cursorLine: selection.active.line,
      cursorCharacter: selection.active.character,
      contentPreview: contentPreview.replace(/\n/g, "\\n"),
    };

    // Capture selection if any
    if (!selection.isEmpty) {
      const selectedText = doc.getText(selection);
      context.selection = {
        selectedText: selectedText.substring(0, 100),
        selectionStart: {
          line: selection.start.line,
          character: selection.start.character,
        },
        selectionEnd: {
          line: selection.end.line,
          character: selection.end.character,
        },
      };
    }
  }

  // Capture workspace info
  if (workspace.workspaceFolders) {
    context.workspace = {
      name: workspace.name || "workspace",
      folders: workspace.workspaceFolders.map((f) => path.basename(f.uri.fsPath)),
      fileCount: 0,
    };
  }

  return context;
}

/**
 * Write context snapshot to file
 */
function logContextToFile(context: ContextSnapshot): void {
  const markdown = `# Copilot Context Window Snapshot

**Captured:** ${context.timestamp}

## Active Editor
${
  context.activeEditor
    ? `
- File: \`${context.activeEditor.fileName}\`
- Language: ${context.activeEditor.language}
- Dirty: ${context.activeEditor.isDirty}
- Lines: ${context.activeEditor.lineCount}
- Cursor: Line ${context.activeEditor.cursorLine}, Char ${context.activeEditor.cursorCharacter}
- Content Preview: \`${context.activeEditor.contentPreview}\`
`
    : "No active editor"
}

## Selection/Cursor
${
  context.selection
    ? `
- Selected Text: \`${context.selection.selectedText}\`
- Start: Line ${context.selection.selectionStart.line}, Char ${context.selection.selectionStart.character}
- End: Line ${context.selection.selectionEnd.line}, Char ${context.selection.selectionEnd.character}
`
    : "No selection"
}

## Workspace
${
  context.workspace
    ? `
- Name: ${context.workspace.name}
- Folders: ${context.workspace.folders.join(", ")}
`
    : "No workspace info"
}

## Open Editors (${context.openEditors.length})
${context.openEditors.map((ed) => `- ${ed.fileName} (${ed.language})`).join("\n")}

---
*Generated by Copilot Context Window Demo*
`;

  fs.writeFileSync(resultsFile, markdown, "utf-8");
}

/**
 * Command: Read and display context
 */
async function readContextCommand(): Promise<void> {
  const context = captureContextWindow();
  logContextToFile(context);

  vscode.window.showInformationMessage(
    `✓ Context captured! Check ${path.basename(resultsFile)}`,
    { modal: false }
  );

  // Also show in console for verification
  console.log("DEMO: Context Window Snapshot");
  console.log(JSON.stringify(context, null, 2));
}

/**
 * Command: Log active editor to a test file
 */
async function logActiveEditorCommand(): Promise<void> {
  const editor = vscode.window.activeTextEditor;
  if (!editor) {
    vscode.window.showWarningMessage("No active editor");
    return;
  }

  const doc = editor.document;
  const testFile = path.join(workspaceDir, "DEMO_ACTIVE_EDITOR_TEST.json");

  const info = {
    success: true,
    test: "log_active_editor",
    data: {
      fileName: path.basename(doc.fileName),
      language: doc.languageId,
      lineCount: doc.lineCount,
      characterCount: doc.getText().length,
      isDirty: doc.isDirty,
      cursorPosition: {
        line: editor.selection.active.line,
        character: editor.selection.active.character,
      },
    },
    timestamp: new Date().toISOString(),
  };

  fs.writeFileSync(testFile, JSON.stringify(info, null, 2), "utf-8");

  vscode.window.showInformationMessage(
    `✓ Active editor logged to ${path.basename(testFile)}`
  );
  console.log("DEMO: Active Editor Info");
  console.log(JSON.stringify(info, null, 2));
}

/**
 * Command: Log selection to a test file
 */
async function logSelectionCommand(): Promise<void> {
  const editor = vscode.window.activeTextEditor;
  if (!editor) {
    vscode.window.showWarningMessage("No active editor");
    return;
  }

  const doc = editor.document;
  const selection = editor.selection;
  const testFile = path.join(workspaceDir, "DEMO_SELECTION_TEST.json");

  const selectedText = doc.getText(selection);
  const info = {
    success: true,
    test: "log_selection",
    data: {
      hasSelection: !selection.isEmpty,
      selectedTextLength: selectedText.length,
      selectedTextPreview: selectedText.substring(0, 50),
      startLine: selection.start.line,
      startCharacter: selection.start.character,
      endLine: selection.end.line,
      endCharacter: selection.end.character,
      fileName: path.basename(doc.fileName),
    },
    timestamp: new Date().toISOString(),
  };

  fs.writeFileSync(testFile, JSON.stringify(info, null, 2), "utf-8");

  vscode.window.showInformationMessage(
    `✓ Selection logged to ${path.basename(testFile)}`
  );
  console.log("DEMO: Selection Info");
  console.log(JSON.stringify(info, null, 2));
}

export function activate(context: vscode.ExtensionContext) {
  console.log(
    "✓ Copilot Context Window Demo activated - commands available"
  );

  // Register commands
  context.subscriptions.push(
    vscode.commands.registerCommand(
      "demo.contextWindow.readContext",
      readContextCommand
    ),
    vscode.commands.registerCommand(
      "demo.contextWindow.logActiveEditor",
      logActiveEditorCommand
    ),
    vscode.commands.registerCommand(
      "demo.contextWindow.logSelection",
      logSelectionCommand
    )
  );
}

export function deactivate() {}
